add landingpage component
ekmigasari/syncsquad pull request #7
Opened 2023-11-30 09:12 UTC by wahyuhjr

2023-11-30 09:13 UTC, wahyuhjr reviewed
add component

2023-11-30 11:39 UTC, indrazm commented on src/app/components/Card/index.jsx
Do not use <img> use <Image>

2023-11-30 11:42 UTC, indrazm requested changes
Please change

2023-12-01 15:16 UTC, indrazm commented on src/components/Button/index.jsx
Don't need `<>`

2023-12-01 15:17 UTC, indrazm approved these changes

2023-12-01 15:21 UTC, ekmigasari approved these changes

2023-12-01 15:22 UTC, merged